:mock_path: "mocks"                      # Good: matches your folder
:includes:
  - "src/data"
  - "src/logic"
  - "src/presentation"
:plugins:
  - expect
  - expect_any_args
  - ignore
:framework: unity
:unity_helper_path: "Unity/auto"
:verbosity: 2
:mock_prefix: "Mock"
:enforce_strict_ordering: false
