# CMAKE generated file: DO NOT EDIT!
# Generated by "MinGW Makefiles" Generator, CMake Version 4.0

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

SHELL = cmd.exe

# The CMake executable.
CMAKE_COMMAND = "C:\Program Files\CMake\bin\cmake.exe"

# The command to remove a file.
RM = "C:\Program Files\CMake\bin\cmake.exe" -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = C:\Users\bojan\CLionProjects\bank-teissl_A_BankProject

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = C:\Users\bojan\CLionProjects\bank-teissl_A_BankProject

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running tests..."
	"C:\Program Files\CMake\bin\ctest.exe" $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test
.PHONY : test/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	"C:\Program Files\CMake\bin\cmake-gui.exe" -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	"C:\Program Files\CMake\bin\cmake.exe" --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start C:\Users\bojan\CLionProjects\bank-teissl_A_BankProject\CMakeFiles C:\Users\bojan\CLionProjects\bank-teissl_A_BankProject\\CMakeFiles\progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start C:\Users\bojan\CLionProjects\bank-teissl_A_BankProject\CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named coverage

# Build rule for target.
coverage: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 coverage
.PHONY : coverage

# fast build rule for target.
coverage/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\coverage.dir\build.make CMakeFiles/coverage.dir/build
.PHONY : coverage/fast

#=============================================================================
# Target rules for targets named BankApp

# Build rule for target.
BankApp: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 BankApp
.PHONY : BankApp

# fast build rule for target.
BankApp/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\BankApp.dir\build.make CMakeFiles/BankApp.dir/build
.PHONY : BankApp/fast

#=============================================================================
# Target rules for targets named test_delete_account

# Build rule for target.
test_delete_account: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 test_delete_account
.PHONY : test_delete_account

# fast build rule for target.
test_delete_account/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\test_delete_account.dir\build.make CMakeFiles/test_delete_account.dir/build
.PHONY : test_delete_account/fast

Tests/test_delete_account.obj: Tests/test_delete_account.c.obj
.PHONY : Tests/test_delete_account.obj

# target to build an object file
Tests/test_delete_account.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\test_delete_account.dir\build.make CMakeFiles/test_delete_account.dir/Tests/test_delete_account.c.obj
.PHONY : Tests/test_delete_account.c.obj

Tests/test_delete_account.i: Tests/test_delete_account.c.i
.PHONY : Tests/test_delete_account.i

# target to preprocess a source file
Tests/test_delete_account.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\test_delete_account.dir\build.make CMakeFiles/test_delete_account.dir/Tests/test_delete_account.c.i
.PHONY : Tests/test_delete_account.c.i

Tests/test_delete_account.s: Tests/test_delete_account.c.s
.PHONY : Tests/test_delete_account.s

# target to generate assembly for a file
Tests/test_delete_account.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\test_delete_account.dir\build.make CMakeFiles/test_delete_account.dir/Tests/test_delete_account.c.s
.PHONY : Tests/test_delete_account.c.s

Tests/unity/unity.obj: Tests/unity/unity.c.obj
.PHONY : Tests/unity/unity.obj

# target to build an object file
Tests/unity/unity.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\test_delete_account.dir\build.make CMakeFiles/test_delete_account.dir/Tests/unity/unity.c.obj
.PHONY : Tests/unity/unity.c.obj

Tests/unity/unity.i: Tests/unity/unity.c.i
.PHONY : Tests/unity/unity.i

# target to preprocess a source file
Tests/unity/unity.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\test_delete_account.dir\build.make CMakeFiles/test_delete_account.dir/Tests/unity/unity.c.i
.PHONY : Tests/unity/unity.c.i

Tests/unity/unity.s: Tests/unity/unity.c.s
.PHONY : Tests/unity/unity.s

# target to generate assembly for a file
Tests/unity/unity.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\test_delete_account.dir\build.make CMakeFiles/test_delete_account.dir/Tests/unity/unity.c.s
.PHONY : Tests/unity/unity.c.s

src/data/account_data.obj: src/data/account_data.c.obj
.PHONY : src/data/account_data.obj

# target to build an object file
src/data/account_data.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\BankApp.dir\build.make CMakeFiles/BankApp.dir/src/data/account_data.c.obj
	$(MAKE) $(MAKESILENT) -f CMakeFiles\test_delete_account.dir\build.make CMakeFiles/test_delete_account.dir/src/data/account_data.c.obj
.PHONY : src/data/account_data.c.obj

src/data/account_data.i: src/data/account_data.c.i
.PHONY : src/data/account_data.i

# target to preprocess a source file
src/data/account_data.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\BankApp.dir\build.make CMakeFiles/BankApp.dir/src/data/account_data.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles\test_delete_account.dir\build.make CMakeFiles/test_delete_account.dir/src/data/account_data.c.i
.PHONY : src/data/account_data.c.i

src/data/account_data.s: src/data/account_data.c.s
.PHONY : src/data/account_data.s

# target to generate assembly for a file
src/data/account_data.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\BankApp.dir\build.make CMakeFiles/BankApp.dir/src/data/account_data.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles\test_delete_account.dir\build.make CMakeFiles/test_delete_account.dir/src/data/account_data.c.s
.PHONY : src/data/account_data.c.s

src/data/transactions_db.obj: src/data/transactions_db.c.obj
.PHONY : src/data/transactions_db.obj

# target to build an object file
src/data/transactions_db.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\BankApp.dir\build.make CMakeFiles/BankApp.dir/src/data/transactions_db.c.obj
.PHONY : src/data/transactions_db.c.obj

src/data/transactions_db.i: src/data/transactions_db.c.i
.PHONY : src/data/transactions_db.i

# target to preprocess a source file
src/data/transactions_db.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\BankApp.dir\build.make CMakeFiles/BankApp.dir/src/data/transactions_db.c.i
.PHONY : src/data/transactions_db.c.i

src/data/transactions_db.s: src/data/transactions_db.c.s
.PHONY : src/data/transactions_db.s

# target to generate assembly for a file
src/data/transactions_db.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\BankApp.dir\build.make CMakeFiles/BankApp.dir/src/data/transactions_db.c.s
.PHONY : src/data/transactions_db.c.s

src/logic/bank_logic.obj: src/logic/bank_logic.c.obj
.PHONY : src/logic/bank_logic.obj

# target to build an object file
src/logic/bank_logic.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\BankApp.dir\build.make CMakeFiles/BankApp.dir/src/logic/bank_logic.c.obj
.PHONY : src/logic/bank_logic.c.obj

src/logic/bank_logic.i: src/logic/bank_logic.c.i
.PHONY : src/logic/bank_logic.i

# target to preprocess a source file
src/logic/bank_logic.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\BankApp.dir\build.make CMakeFiles/BankApp.dir/src/logic/bank_logic.c.i
.PHONY : src/logic/bank_logic.c.i

src/logic/bank_logic.s: src/logic/bank_logic.c.s
.PHONY : src/logic/bank_logic.s

# target to generate assembly for a file
src/logic/bank_logic.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\BankApp.dir\build.make CMakeFiles/BankApp.dir/src/logic/bank_logic.c.s
.PHONY : src/logic/bank_logic.c.s

src/logic/controller.obj: src/logic/controller.c.obj
.PHONY : src/logic/controller.obj

# target to build an object file
src/logic/controller.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\BankApp.dir\build.make CMakeFiles/BankApp.dir/src/logic/controller.c.obj
.PHONY : src/logic/controller.c.obj

src/logic/controller.i: src/logic/controller.c.i
.PHONY : src/logic/controller.i

# target to preprocess a source file
src/logic/controller.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\BankApp.dir\build.make CMakeFiles/BankApp.dir/src/logic/controller.c.i
.PHONY : src/logic/controller.c.i

src/logic/controller.s: src/logic/controller.c.s
.PHONY : src/logic/controller.s

# target to generate assembly for a file
src/logic/controller.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\BankApp.dir\build.make CMakeFiles/BankApp.dir/src/logic/controller.c.s
.PHONY : src/logic/controller.c.s

src/logic/create_account.obj: src/logic/create_account.c.obj
.PHONY : src/logic/create_account.obj

# target to build an object file
src/logic/create_account.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\BankApp.dir\build.make CMakeFiles/BankApp.dir/src/logic/create_account.c.obj
.PHONY : src/logic/create_account.c.obj

src/logic/create_account.i: src/logic/create_account.c.i
.PHONY : src/logic/create_account.i

# target to preprocess a source file
src/logic/create_account.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\BankApp.dir\build.make CMakeFiles/BankApp.dir/src/logic/create_account.c.i
.PHONY : src/logic/create_account.c.i

src/logic/create_account.s: src/logic/create_account.c.s
.PHONY : src/logic/create_account.s

# target to generate assembly for a file
src/logic/create_account.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\BankApp.dir\build.make CMakeFiles/BankApp.dir/src/logic/create_account.c.s
.PHONY : src/logic/create_account.c.s

src/logic/delete_account.obj: src/logic/delete_account.c.obj
.PHONY : src/logic/delete_account.obj

# target to build an object file
src/logic/delete_account.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\BankApp.dir\build.make CMakeFiles/BankApp.dir/src/logic/delete_account.c.obj
	$(MAKE) $(MAKESILENT) -f CMakeFiles\test_delete_account.dir\build.make CMakeFiles/test_delete_account.dir/src/logic/delete_account.c.obj
.PHONY : src/logic/delete_account.c.obj

src/logic/delete_account.i: src/logic/delete_account.c.i
.PHONY : src/logic/delete_account.i

# target to preprocess a source file
src/logic/delete_account.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\BankApp.dir\build.make CMakeFiles/BankApp.dir/src/logic/delete_account.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles\test_delete_account.dir\build.make CMakeFiles/test_delete_account.dir/src/logic/delete_account.c.i
.PHONY : src/logic/delete_account.c.i

src/logic/delete_account.s: src/logic/delete_account.c.s
.PHONY : src/logic/delete_account.s

# target to generate assembly for a file
src/logic/delete_account.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\BankApp.dir\build.make CMakeFiles/BankApp.dir/src/logic/delete_account.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles\test_delete_account.dir\build.make CMakeFiles/test_delete_account.dir/src/logic/delete_account.c.s
.PHONY : src/logic/delete_account.c.s

src/logic/update_account.obj: src/logic/update_account.c.obj
.PHONY : src/logic/update_account.obj

# target to build an object file
src/logic/update_account.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\BankApp.dir\build.make CMakeFiles/BankApp.dir/src/logic/update_account.c.obj
.PHONY : src/logic/update_account.c.obj

src/logic/update_account.i: src/logic/update_account.c.i
.PHONY : src/logic/update_account.i

# target to preprocess a source file
src/logic/update_account.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\BankApp.dir\build.make CMakeFiles/BankApp.dir/src/logic/update_account.c.i
.PHONY : src/logic/update_account.c.i

src/logic/update_account.s: src/logic/update_account.c.s
.PHONY : src/logic/update_account.s

# target to generate assembly for a file
src/logic/update_account.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\BankApp.dir\build.make CMakeFiles/BankApp.dir/src/logic/update_account.c.s
.PHONY : src/logic/update_account.c.s

src/logic/validations.obj: src/logic/validations.c.obj
.PHONY : src/logic/validations.obj

# target to build an object file
src/logic/validations.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\BankApp.dir\build.make CMakeFiles/BankApp.dir/src/logic/validations.c.obj
.PHONY : src/logic/validations.c.obj

src/logic/validations.i: src/logic/validations.c.i
.PHONY : src/logic/validations.i

# target to preprocess a source file
src/logic/validations.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\BankApp.dir\build.make CMakeFiles/BankApp.dir/src/logic/validations.c.i
.PHONY : src/logic/validations.c.i

src/logic/validations.s: src/logic/validations.c.s
.PHONY : src/logic/validations.s

# target to generate assembly for a file
src/logic/validations.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\BankApp.dir\build.make CMakeFiles/BankApp.dir/src/logic/validations.c.s
.PHONY : src/logic/validations.c.s

src/main.obj: src/main.c.obj
.PHONY : src/main.obj

# target to build an object file
src/main.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\BankApp.dir\build.make CMakeFiles/BankApp.dir/src/main.c.obj
.PHONY : src/main.c.obj

src/main.i: src/main.c.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\BankApp.dir\build.make CMakeFiles/BankApp.dir/src/main.c.i
.PHONY : src/main.c.i

src/main.s: src/main.c.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\BankApp.dir\build.make CMakeFiles/BankApp.dir/src/main.c.s
.PHONY : src/main.c.s

src/presentation/user_interface.obj: src/presentation/user_interface.c.obj
.PHONY : src/presentation/user_interface.obj

# target to build an object file
src/presentation/user_interface.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\BankApp.dir\build.make CMakeFiles/BankApp.dir/src/presentation/user_interface.c.obj
.PHONY : src/presentation/user_interface.c.obj

src/presentation/user_interface.i: src/presentation/user_interface.c.i
.PHONY : src/presentation/user_interface.i

# target to preprocess a source file
src/presentation/user_interface.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\BankApp.dir\build.make CMakeFiles/BankApp.dir/src/presentation/user_interface.c.i
.PHONY : src/presentation/user_interface.c.i

src/presentation/user_interface.s: src/presentation/user_interface.c.s
.PHONY : src/presentation/user_interface.s

# target to generate assembly for a file
src/presentation/user_interface.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\BankApp.dir\build.make CMakeFiles/BankApp.dir/src/presentation/user_interface.c.s
.PHONY : src/presentation/user_interface.c.s

# Help Target
help:
	@echo The following are some of the valid targets for this Makefile:
	@echo ... all (the default if no target is provided)
	@echo ... clean
	@echo ... depend
	@echo ... edit_cache
	@echo ... rebuild_cache
	@echo ... test
	@echo ... coverage
	@echo ... BankApp
	@echo ... test_delete_account
	@echo ... Tests/test_delete_account.obj
	@echo ... Tests/test_delete_account.i
	@echo ... Tests/test_delete_account.s
	@echo ... Tests/unity/unity.obj
	@echo ... Tests/unity/unity.i
	@echo ... Tests/unity/unity.s
	@echo ... src/data/account_data.obj
	@echo ... src/data/account_data.i
	@echo ... src/data/account_data.s
	@echo ... src/data/transactions_db.obj
	@echo ... src/data/transactions_db.i
	@echo ... src/data/transactions_db.s
	@echo ... src/logic/bank_logic.obj
	@echo ... src/logic/bank_logic.i
	@echo ... src/logic/bank_logic.s
	@echo ... src/logic/controller.obj
	@echo ... src/logic/controller.i
	@echo ... src/logic/controller.s
	@echo ... src/logic/create_account.obj
	@echo ... src/logic/create_account.i
	@echo ... src/logic/create_account.s
	@echo ... src/logic/delete_account.obj
	@echo ... src/logic/delete_account.i
	@echo ... src/logic/delete_account.s
	@echo ... src/logic/update_account.obj
	@echo ... src/logic/update_account.i
	@echo ... src/logic/update_account.s
	@echo ... src/logic/validations.obj
	@echo ... src/logic/validations.i
	@echo ... src/logic/validations.s
	@echo ... src/main.obj
	@echo ... src/main.i
	@echo ... src/main.s
	@echo ... src/presentation/user_interface.obj
	@echo ... src/presentation/user_interface.i
	@echo ... src/presentation/user_interface.s
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 0
.PHONY : cmake_check_build_system

