/* AUTOGENERATED FILE. DO NOT EDIT. */
#ifndef _MOCKUSER_INTERFACE_H
#define _MOCKUSER_INTERFACE_H

#include "unity.h"
#include "user_interface.h"

/* Ignore the following warnings, since we are copying code */
#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if __GNUC__ > 4 || (__GNUC__ == 4 && (__GNUC_MINOR__ > 6 || (__GNUC_MINOR__ == 6 && __GNUC_PATCHLEVEL__ > 0)))
#pragma GCC diagnostic push
#endif
#if !defined(__clang__)
#pragma GCC diagnostic ignored "-Wpragmas"
#endif
#pragma GCC diagnostic ignored "-Wunknown-pragmas"
#pragma GCC diagnostic ignored "-Wduplicate-decl-specifier"
#endif

#ifdef __cplusplus
extern "C" {
#endif

void Mockuser_interface_Init(void);
void Mockuser_interface_Destroy(void);
void Mockuser_interface_Verify(void);


typedef int(*cmock_user_interface_func_ptr1)(const char*);


#define open_file_error_ExpectAndReturn(cmock_retval) TEST_FAIL_MESSAGE("open_file_error requires _Expect (not AndReturn)");
#define open_file_error_Expect() open_file_error_CMockExpect(__LINE__)
void open_file_error_CMockExpect(UNITY_LINE_TYPE cmock_line);
#define print_account_confirmation_ExpectAndReturn(account, cmock_retval) TEST_FAIL_MESSAGE("print_account_confirmation requires _Expect (not AndReturn)");
#define print_account_confirmation_Expect(account) print_account_confirmation_CMockExpect(__LINE__, account)
void print_account_confirmation_CMockExpect(UNITY_LINE_TYPE cmock_line, const BankAccount* account);
#define get_nonempty_input_ExpectAndReturn(prompt, buffer, cmock_retval) TEST_FAIL_MESSAGE("get_nonempty_input requires _Expect (not AndReturn)");
#define get_nonempty_input_Expect(prompt, buffer) get_nonempty_input_CMockExpect(__LINE__, prompt, buffer)
void get_nonempty_input_CMockExpect(UNITY_LINE_TYPE cmock_line, const char* prompt, char* buffer);
#define get_validated_input_ExpectAndReturn(prompt, buffer, size, validate, error_msg, cmock_retval) TEST_FAIL_MESSAGE("get_validated_input requires _Expect (not AndReturn)");
#define get_validated_input_Expect(prompt, buffer, size, validate, error_msg) get_validated_input_CMockExpect(__LINE__, prompt, buffer, size, validate, error_msg)
void get_validated_input_CMockExpect(UNITY_LINE_TYPE cmock_line, const char* prompt, char* buffer, int size, cmock_user_interface_func_ptr1 validate, const char* error_msg);

#ifdef __cplusplus
}
#endif

#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if __GNUC__ > 4 || (__GNUC__ == 4 && (__GNUC_MINOR__ > 6 || (__GNUC_MINOR__ == 6 && __GNUC_PATCHLEVEL__ > 0)))
#pragma GCC diagnostic pop
#endif
#endif

#endif
