/* AUTOGENERATED FILE. DO NOT EDIT. */
#include <string.h>
#include <stdlib.h>
#include <setjmp.h>
#include "Tests/CMock/src/cmock.h"
#include "Mockaccount_data.h"

static const char* CMockString_account = "account";
static const char* CMockString_account_exists = "account_exists";
static const char* CMockString_account_number = "account_number";
static const char* CMockString_filename = "filename";
static const char* CMockString_get_account_by_account_number = "get_account_by_account_number";
static const char* CMockString_remove_account = "remove_account";
static const char* CMockString_save_account_to_csv = "save_account_to_csv";

typedef struct _CMOCK_account_exists_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  bool ReturnVal;
  const char* Expected_filename;
  const char* Expected_account_number;

} CMOCK_account_exists_CALL_INSTANCE;

typedef struct _CMOCK_save_account_to_csv_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  int ReturnVal;
  const char* Expected_filename;
  const BankAccount* Expected_account;

} CMOCK_save_account_to_csv_CALL_INSTANCE;

typedef struct _CMOCK_get_account_by_account_number_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  int ReturnVal;
  const char* Expected_filename;
  const char* Expected_account_number;
  BankAccount* Expected_account;

} CMOCK_get_account_by_account_number_CALL_INSTANCE;

typedef struct _CMOCK_remove_account_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  int ReturnVal;
  const char* Expected_filename;
  const BankAccount* Expected_account;

} CMOCK_remove_account_CALL_INSTANCE;

static struct Mockaccount_dataInstance
{
  CMOCK_MEM_INDEX_TYPE account_exists_CallInstance;
  CMOCK_MEM_INDEX_TYPE save_account_to_csv_CallInstance;
  CMOCK_MEM_INDEX_TYPE get_account_by_account_number_CallInstance;
  CMOCK_MEM_INDEX_TYPE remove_account_CallInstance;
} Mock;


void Mockaccount_data_Verify(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_MEM_INDEX_TYPE call_instance;
  call_instance = Mock.account_exists_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_account_exists);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.save_account_to_csv_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_save_account_to_csv);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.get_account_by_account_number_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_get_account_by_account_number);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.remove_account_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_remove_account);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
}

void Mockaccount_data_Init(void)
{
  Mockaccount_data_Destroy();
}

void Mockaccount_data_Destroy(void)
{
  CMock_Guts_MemFreeAll();
  memset(&Mock, 0, sizeof(Mock));
}

bool account_exists(const char* filename, const char* account_number)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_account_exists_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_account_exists);
  cmock_call_instance = (CMOCK_account_exists_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.account_exists_CallInstance);
  Mock.account_exists_CallInstance = CMock_Guts_MemNext(Mock.account_exists_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_account_exists,CMockString_filename);
    UNITY_TEST_ASSERT_EQUAL_STRING(cmock_call_instance->Expected_filename, filename, cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_account_exists,CMockString_account_number);
    UNITY_TEST_ASSERT_EQUAL_STRING(cmock_call_instance->Expected_account_number, account_number, cmock_line, CMockStringMismatch);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_account_exists(CMOCK_account_exists_CALL_INSTANCE* cmock_call_instance, const char* filename, const char* account_number);
void CMockExpectParameters_account_exists(CMOCK_account_exists_CALL_INSTANCE* cmock_call_instance, const char* filename, const char* account_number)
{
  cmock_call_instance->Expected_filename = filename;
  cmock_call_instance->Expected_account_number = account_number;
}

void account_exists_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, const char* filename, const char* account_number, bool cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_account_exists_CALL_INSTANCE));
  CMOCK_account_exists_CALL_INSTANCE* cmock_call_instance = (CMOCK_account_exists_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.account_exists_CallInstance = CMock_Guts_MemChain(Mock.account_exists_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_account_exists(cmock_call_instance, filename, account_number);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

int save_account_to_csv(const char* filename, const BankAccount* account)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_save_account_to_csv_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_save_account_to_csv);
  cmock_call_instance = (CMOCK_save_account_to_csv_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.save_account_to_csv_CallInstance);
  Mock.save_account_to_csv_CallInstance = CMock_Guts_MemNext(Mock.save_account_to_csv_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_save_account_to_csv,CMockString_filename);
    UNITY_TEST_ASSERT_EQUAL_STRING(cmock_call_instance->Expected_filename, filename, cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_save_account_to_csv,CMockString_account);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_account), (void*)(account), sizeof(const BankAccount), cmock_line, CMockStringMismatch);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_save_account_to_csv(CMOCK_save_account_to_csv_CALL_INSTANCE* cmock_call_instance, const char* filename, const BankAccount* account);
void CMockExpectParameters_save_account_to_csv(CMOCK_save_account_to_csv_CALL_INSTANCE* cmock_call_instance, const char* filename, const BankAccount* account)
{
  cmock_call_instance->Expected_filename = filename;
  cmock_call_instance->Expected_account = account;
}

void save_account_to_csv_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, const char* filename, const BankAccount* account, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_save_account_to_csv_CALL_INSTANCE));
  CMOCK_save_account_to_csv_CALL_INSTANCE* cmock_call_instance = (CMOCK_save_account_to_csv_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.save_account_to_csv_CallInstance = CMock_Guts_MemChain(Mock.save_account_to_csv_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_save_account_to_csv(cmock_call_instance, filename, account);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

int get_account_by_account_number(const char* filename, const char* account_number, BankAccount* account)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_get_account_by_account_number_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_get_account_by_account_number);
  cmock_call_instance = (CMOCK_get_account_by_account_number_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.get_account_by_account_number_CallInstance);
  Mock.get_account_by_account_number_CallInstance = CMock_Guts_MemNext(Mock.get_account_by_account_number_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_get_account_by_account_number,CMockString_filename);
    UNITY_TEST_ASSERT_EQUAL_STRING(cmock_call_instance->Expected_filename, filename, cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_get_account_by_account_number,CMockString_account_number);
    UNITY_TEST_ASSERT_EQUAL_STRING(cmock_call_instance->Expected_account_number, account_number, cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_get_account_by_account_number,CMockString_account);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_account), (void*)(account), sizeof(BankAccount), cmock_line, CMockStringMismatch);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_get_account_by_account_number(CMOCK_get_account_by_account_number_CALL_INSTANCE* cmock_call_instance, const char* filename, const char* account_number, BankAccount* account);
void CMockExpectParameters_get_account_by_account_number(CMOCK_get_account_by_account_number_CALL_INSTANCE* cmock_call_instance, const char* filename, const char* account_number, BankAccount* account)
{
  cmock_call_instance->Expected_filename = filename;
  cmock_call_instance->Expected_account_number = account_number;
  cmock_call_instance->Expected_account = account;
}

void get_account_by_account_number_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, const char* filename, const char* account_number, BankAccount* account, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_get_account_by_account_number_CALL_INSTANCE));
  CMOCK_get_account_by_account_number_CALL_INSTANCE* cmock_call_instance = (CMOCK_get_account_by_account_number_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.get_account_by_account_number_CallInstance = CMock_Guts_MemChain(Mock.get_account_by_account_number_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_get_account_by_account_number(cmock_call_instance, filename, account_number, account);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

int remove_account(const char* filename, const BankAccount* account)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_remove_account_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_remove_account);
  cmock_call_instance = (CMOCK_remove_account_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.remove_account_CallInstance);
  Mock.remove_account_CallInstance = CMock_Guts_MemNext(Mock.remove_account_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_remove_account,CMockString_filename);
    UNITY_TEST_ASSERT_EQUAL_STRING(cmock_call_instance->Expected_filename, filename, cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_remove_account,CMockString_account);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_account), (void*)(account), sizeof(const BankAccount), cmock_line, CMockStringMismatch);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_remove_account(CMOCK_remove_account_CALL_INSTANCE* cmock_call_instance, const char* filename, const BankAccount* account);
void CMockExpectParameters_remove_account(CMOCK_remove_account_CALL_INSTANCE* cmock_call_instance, const char* filename, const BankAccount* account)
{
  cmock_call_instance->Expected_filename = filename;
  cmock_call_instance->Expected_account = account;
}

void remove_account_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, const char* filename, const BankAccount* account, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_remove_account_CALL_INSTANCE));
  CMOCK_remove_account_CALL_INSTANCE* cmock_call_instance = (CMOCK_remove_account_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.remove_account_CallInstance = CMock_Guts_MemChain(Mock.remove_account_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_remove_account(cmock_call_instance, filename, account);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

