/* AUTOGENERATED FILE. DO NOT EDIT. */
#include <string.h>
#include <stdlib.h>
#include <setjmp.h>
#include "cmock.h"
#include "Mockcreate_account.h"

static const char* CMockString_account = "account";
static const char* CMockString_branch_code = "branch_code";
static const char* CMockString_create_account_logic = "create_account_logic";
static const char* CMockString_generate_unique_account_number = "generate_unique_account_number";
static const char* CMockString_is_valid_branch_code = "is_valid_branch_code";
static const char* CMockString_is_valid_ssn = "is_valid_ssn";
static const char* CMockString_ssn = "ssn";
static const char* CMockString_start_account_creation_ui = "start_account_creation_ui";

typedef struct _CMOCK_create_account_logic_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;

} CMOCK_create_account_logic_CALL_INSTANCE;

typedef struct _CMOCK_generate_unique_account_number_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char* ReturnVal;

} CMOCK_generate_unique_account_number_CALL_INSTANCE;

typedef struct _CMOCK_start_account_creation_ui_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  BankAccount* Expected_account;

} CMOCK_start_account_creation_ui_CALL_INSTANCE;

typedef struct _CMOCK_is_valid_ssn_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  int ReturnVal;
  const char* Expected_ssn;

} CMOCK_is_valid_ssn_CALL_INSTANCE;

typedef struct _CMOCK_is_valid_branch_code_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  int ReturnVal;
  const char* Expected_branch_code;

} CMOCK_is_valid_branch_code_CALL_INSTANCE;

static struct Mockcreate_accountInstance
{
  CMOCK_MEM_INDEX_TYPE create_account_logic_CallInstance;
  CMOCK_MEM_INDEX_TYPE generate_unique_account_number_CallInstance;
  CMOCK_MEM_INDEX_TYPE start_account_creation_ui_CallInstance;
  CMOCK_MEM_INDEX_TYPE is_valid_ssn_CallInstance;
  CMOCK_MEM_INDEX_TYPE is_valid_branch_code_CallInstance;
} Mock;


void Mockcreate_account_Verify(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_MEM_INDEX_TYPE call_instance;
  call_instance = Mock.create_account_logic_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_create_account_logic);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.generate_unique_account_number_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_generate_unique_account_number);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.start_account_creation_ui_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_start_account_creation_ui);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.is_valid_ssn_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_is_valid_ssn);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.is_valid_branch_code_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_is_valid_branch_code);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
}

void Mockcreate_account_Init(void)
{
  Mockcreate_account_Destroy();
}

void Mockcreate_account_Destroy(void)
{
  CMock_Guts_MemFreeAll();
  memset(&Mock, 0, sizeof(Mock));
}

void create_account_logic(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_create_account_logic_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_create_account_logic);
  cmock_call_instance = (CMOCK_create_account_logic_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.create_account_logic_CallInstance);
  Mock.create_account_logic_CallInstance = CMock_Guts_MemNext(Mock.create_account_logic_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  UNITY_CLR_DETAILS();
}

void create_account_logic_CMockExpect(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_create_account_logic_CALL_INSTANCE));
  CMOCK_create_account_logic_CALL_INSTANCE* cmock_call_instance = (CMOCK_create_account_logic_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.create_account_logic_CallInstance = CMock_Guts_MemChain(Mock.create_account_logic_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
}

char* generate_unique_account_number(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_generate_unique_account_number_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_generate_unique_account_number);
  cmock_call_instance = (CMOCK_generate_unique_account_number_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.generate_unique_account_number_CallInstance);
  Mock.generate_unique_account_number_CallInstance = CMock_Guts_MemNext(Mock.generate_unique_account_number_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void generate_unique_account_number_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, char* cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_generate_unique_account_number_CALL_INSTANCE));
  CMOCK_generate_unique_account_number_CALL_INSTANCE* cmock_call_instance = (CMOCK_generate_unique_account_number_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.generate_unique_account_number_CallInstance = CMock_Guts_MemChain(Mock.generate_unique_account_number_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void start_account_creation_ui(BankAccount* account)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_start_account_creation_ui_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_start_account_creation_ui);
  cmock_call_instance = (CMOCK_start_account_creation_ui_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.start_account_creation_ui_CallInstance);
  Mock.start_account_creation_ui_CallInstance = CMock_Guts_MemNext(Mock.start_account_creation_ui_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_start_account_creation_ui,CMockString_account);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_account), (void*)(account), sizeof(BankAccount), cmock_line, CMockStringMismatch);
  }
  UNITY_CLR_DETAILS();
}

void CMockExpectParameters_start_account_creation_ui(CMOCK_start_account_creation_ui_CALL_INSTANCE* cmock_call_instance, BankAccount* account);
void CMockExpectParameters_start_account_creation_ui(CMOCK_start_account_creation_ui_CALL_INSTANCE* cmock_call_instance, BankAccount* account)
{
  cmock_call_instance->Expected_account = account;
}

void start_account_creation_ui_CMockExpect(UNITY_LINE_TYPE cmock_line, BankAccount* account)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_start_account_creation_ui_CALL_INSTANCE));
  CMOCK_start_account_creation_ui_CALL_INSTANCE* cmock_call_instance = (CMOCK_start_account_creation_ui_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.start_account_creation_ui_CallInstance = CMock_Guts_MemChain(Mock.start_account_creation_ui_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_start_account_creation_ui(cmock_call_instance, account);
}

int is_valid_ssn(const char* ssn)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_is_valid_ssn_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_is_valid_ssn);
  cmock_call_instance = (CMOCK_is_valid_ssn_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.is_valid_ssn_CallInstance);
  Mock.is_valid_ssn_CallInstance = CMock_Guts_MemNext(Mock.is_valid_ssn_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_is_valid_ssn,CMockString_ssn);
    UNITY_TEST_ASSERT_EQUAL_STRING(cmock_call_instance->Expected_ssn, ssn, cmock_line, CMockStringMismatch);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_is_valid_ssn(CMOCK_is_valid_ssn_CALL_INSTANCE* cmock_call_instance, const char* ssn);
void CMockExpectParameters_is_valid_ssn(CMOCK_is_valid_ssn_CALL_INSTANCE* cmock_call_instance, const char* ssn)
{
  cmock_call_instance->Expected_ssn = ssn;
}

void is_valid_ssn_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, const char* ssn, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_is_valid_ssn_CALL_INSTANCE));
  CMOCK_is_valid_ssn_CALL_INSTANCE* cmock_call_instance = (CMOCK_is_valid_ssn_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.is_valid_ssn_CallInstance = CMock_Guts_MemChain(Mock.is_valid_ssn_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_is_valid_ssn(cmock_call_instance, ssn);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

int is_valid_branch_code(const char* branch_code)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_is_valid_branch_code_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_is_valid_branch_code);
  cmock_call_instance = (CMOCK_is_valid_branch_code_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.is_valid_branch_code_CallInstance);
  Mock.is_valid_branch_code_CallInstance = CMock_Guts_MemNext(Mock.is_valid_branch_code_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_is_valid_branch_code,CMockString_branch_code);
    UNITY_TEST_ASSERT_EQUAL_STRING(cmock_call_instance->Expected_branch_code, branch_code, cmock_line, CMockStringMismatch);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_is_valid_branch_code(CMOCK_is_valid_branch_code_CALL_INSTANCE* cmock_call_instance, const char* branch_code);
void CMockExpectParameters_is_valid_branch_code(CMOCK_is_valid_branch_code_CALL_INSTANCE* cmock_call_instance, const char* branch_code)
{
  cmock_call_instance->Expected_branch_code = branch_code;
}

void is_valid_branch_code_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, const char* branch_code, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_is_valid_branch_code_CALL_INSTANCE));
  CMOCK_is_valid_branch_code_CALL_INSTANCE* cmock_call_instance = (CMOCK_is_valid_branch_code_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.is_valid_branch_code_CallInstance = CMock_Guts_MemChain(Mock.is_valid_branch_code_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_is_valid_branch_code(cmock_call_instance, branch_code);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

